ALTER TABLE chat_rooms DROP FOREIGN KEY chat_rooms_ibfk_1;
ALTER TABLE chat_room_members DROP FOREIGN KEY chat_room_members_ibfk_2;
ALTER TABLE chat_room_members DROP FOREIGN KEY FK_5769079E54177093;
DROP INDEX fk_5769079e54177093 ON chat_room_members;
CREATE INDEX IDX_5769079E54177093 ON chat_room_members (room_id);
ALTER TABLE chat_room_members ADD CONSTRAINT FK_5769079E54177093 FOREIGN KEY (room_id) REFERENCES chat_rooms (id);
ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_2;
ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_3;
ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_1;
ALTER TABLE community_groups DROP FOREIGN KEY community_groups_ibfk_1;
ALTER TABLE contracts DROP FOREIGN KEY contracts_ibfk_3;
ALTER TABLE contracts DROP FOREIGN KEY contracts_ibfk_1;
ALTER TABLE contracts DROP FOREIGN KEY contracts_ibfk_2;
ALTER TABLE departments DROP FOREIGN KEY fk_dept_manager;
ALTER TABLE group_members DROP INDEX FK_C3A086F3FE54D947, ADD UNIQUE INDEX UNIQ_C3A086F3FE54D947 (group_id);
ALTER TABLE interviews DROP FOREIGN KEY interviews_ibfk_3;
ALTER TABLE interviews DROP FOREIGN KEY interviews_ibfk_1;
ALTER TABLE interviews DROP FOREIGN KEY interviews_ibfk_4;
ALTER TABLE interviews DROP FOREIGN KEY interviews_ibfk_2;
ALTER TABLE job_applications DROP FOREIGN KEY job_applications_ibfk_1;
ALTER TABLE job_applications DROP FOREIGN KEY job_applications_ibfk_2;
ALTER TABLE leaves DROP FOREIGN KEY leaves_ibfk_1;
ALTER TABLE messages DROP FOREIGN KEY messages_ibfk_1;
ALTER TABLE messages DROP FOREIGN KEY messages_ibfk_2;
ALTER TABLE notifications DROP FOREIGN KEY notifications_ibfk_1;
ALTER TABLE offers DROP FOREIGN KEY offers_ibfk_1;
ALTER TABLE offers DROP FOREIGN KEY offers_ibfk_2;
ALTER TABLE payrolls DROP FOREIGN KEY payrolls_ibfk_1;
ALTER TABLE posts DROP FOREIGN KEY posts_ibfk_1;
ALTER TABLE posts DROP FOREIGN KEY posts_ibfk_2;
ALTER TABLE projects DROP FOREIGN KEY projects_ibfk_2;
ALTER TABLE projects DROP FOREIGN KEY projects_ibfk_1;
ALTER TABLE project_members DROP INDEX FK_D3BEDE9A166D1F9C, ADD UNIQUE INDEX UNIQ_D3BEDE9A166D1F9C (project_id);
ALTER TABLE reactions DROP FOREIGN KEY reactions_ibfk_1;
ALTER TABLE reactions DROP FOREIGN KEY reactions_ibfk_2;
ALTER TABLE tasks DROP FOREIGN KEY tasks_ibfk_1;
ALTER TABLE tasks DROP FOREIGN KEY tasks_ibfk_2;
ALTER TABLE training_certificates DROP FOREIGN KEY training_certificates_ibfk_1;
ALTER TABLE training_certificates DROP FOREIGN KEY training_certificates_ibfk_2;
ALTER TABLE training_certificates DROP FOREIGN KEY training_certificates_ibfk_3;
ALTER TABLE training_courses DROP FOREIGN KEY training_courses_ibfk_1;
ALTER TABLE training_enrollments DROP INDEX FK_68B3BBE5591CC992, ADD UNIQUE INDEX UNIQ_68B3BBE5591CC992 (course_id);
ALTER TABLE user DROP FOREIGN KEY user_ibfk_1;
ALTER TABLE user_follows DROP INDEX FK_136E9479AC24F853, ADD UNIQUE INDEX UNIQ_136E9479AC24F853 (follower_id);
