ALTER TABLE calls DROP FOREIGN KEY FK_DAA35C8F68AC0374;
ALTER TABLE calls DROP FOREIGN KEY FK_DAA35C8FA5626C52;
DROP INDEX fk_daa35c8fa5626c52 ON calls;
CREATE INDEX IDX_DAA35C8FA5626C52 ON calls (caller_id);
DROP INDEX fk_daa35c8f68ac0374 ON calls;
CREATE INDEX IDX_DAA35C8F68AC0374 ON calls (callee_id);
ALTER TABLE calls ADD CONSTRAINT FK_DAA35C8F68AC0374 FOREIGN KEY (callee_id) REFERENCES user (id);
ALTER TABLE calls ADD CONSTRAINT FK_DAA35C8FA5626C52 FOREIGN KEY (caller_id) REFERENCES user (id);
ALTER TABLE chat_rooms DROP FOREIGN KEY chat_rooms_ibfk_1;
ALTER TABLE chat_rooms DROP FOREIGN KEY chat_rooms_ibfk_1;
ALTER TABLE chat_rooms CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE chat_rooms ADD CONSTRAINT FK_7DDCF70DDE12AB56 FOREIGN KEY (created_by) REFERENCES user (id);
DROP INDEX created_by ON chat_rooms;
CREATE INDEX IDX_7DDCF70DDE12AB56 ON chat_rooms (created_by);
ALTER TABLE chat_rooms ADD CONSTRAINT chat_rooms_ibfk_1 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL;
ALTER TABLE chat_room_members DROP FOREIGN KEY chat_room_members_ibfk_1;
ALTER TABLE chat_room_members DROP FOREIGN KEY chat_room_members_ibfk_2;
DROP INDEX unique_room_member ON chat_room_members;
ALTER TABLE chat_room_members DROP FOREIGN KEY chat_room_members_ibfk_2;
ALTER TABLE chat_room_members CHANGE room_id room_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE role role VARCHAR(255) DEFAULT NULL, CHANGE joined_at joined_at DATETIME NOT NULL;
ALTER TABLE chat_room_members ADD CONSTRAINT FK_5769079E54177093 FOREIGN KEY (room_id) REFERENCES chat_rooms (id);
ALTER TABLE chat_room_members ADD CONSTRAINT FK_5769079EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
DROP INDEX user_id ON chat_room_members;
CREATE INDEX IDX_5769079EA76ED395 ON chat_room_members (user_id);
ALTER TABLE chat_room_members ADD CONSTRAINT chat_room_members_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_1;
ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_2;
ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_3;
ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_1;
ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_2;
ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_3;
ALTER TABLE comments CHANGE post_id post_id INT DEFAULT NULL, CHANGE author_id author_id INT DEFAULT NULL, CHANGE content content LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A4B89032C FOREIGN KEY (post_id) REFERENCES posts (id);
ALTER TABLE comments ADD CONSTRAINT FK_5F9E962AF675F31B FOREIGN KEY (author_id) REFERENCES user (id);
ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A727ACA70 FOREIGN KEY (parent_id) REFERENCES comments (id);
DROP INDEX post_id ON comments;
CREATE INDEX IDX_5F9E962A4B89032C ON comments (post_id);
DROP INDEX author_id ON comments;
CREATE INDEX IDX_5F9E962AF675F31B ON comments (author_id);
DROP INDEX parent_id ON comments;
CREATE INDEX IDX_5F9E962A727ACA70 ON comments (parent_id);
ALTER TABLE comments ADD CONSTRAINT comments_ibfk_1 FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE;
ALTER TABLE comments ADD CONSTRAINT comments_ibfk_2 FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE comments ADD CONSTRAINT comments_ibfk_3 FOREIGN KEY (parent_id) REFERENCES comments (id) ON DELETE CASCADE;
ALTER TABLE community_groups DROP FOREIGN KEY community_groups_ibfk_1;
ALTER TABLE community_groups DROP FOREIGN KEY community_groups_ibfk_1;
ALTER TABLE community_groups CHANGE description description LONGTEXT DEFAULT NULL, CHANGE privacy privacy VARCHAR(255) DEFAULT NULL, CHANGE member_count member_count INT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE community_groups ADD CONSTRAINT FK_81A7CC8361220EA6 FOREIGN KEY (creator_id) REFERENCES user (id);
DROP INDEX creator_id ON community_groups;
CREATE INDEX IDX_81A7CC8361220EA6 ON community_groups (creator_id);
ALTER TABLE community_groups ADD CONSTRAINT community_groups_ibfk_1 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL;
ALTER TABLE contracts DROP FOREIGN KEY contracts_ibfk_3;
ALTER TABLE contracts DROP FOREIGN KEY contracts_ibfk_1;
ALTER TABLE contracts DROP FOREIGN KEY contracts_ibfk_2;
ALTER TABLE contracts DROP FOREIGN KEY contracts_ibfk_3;
ALTER TABLE contracts DROP FOREIGN KEY contracts_ibfk_1;
ALTER TABLE contracts DROP FOREIGN KEY contracts_ibfk_2;
ALTER TABLE contracts CHANGE offer_id offer_id INT DEFAULT NULL, CHANGE applicant_id applicant_id INT DEFAULT NULL, CHANGE owner_id owner_id INT DEFAULT NULL, CHANGE terms terms LONGTEXT DEFAULT NULL, CHANGE amount amount DOUBLE PRECISION DEFAULT NULL, CHANGE currency currency VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE risk_factors risk_factors LONGTEXT DEFAULT NULL, CHANGE blockchain_hash blockchain_hash VARCHAR(255) DEFAULT NULL, CHANGE qr_code_url qr_code_url VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE counter_terms counter_terms LONGTEXT DEFAULT NULL, CHANGE negotiation_notes negotiation_notes LONGTEXT DEFAULT NULL, CHANGE negotiation_round negotiation_round INT DEFAULT NULL;
ALTER TABLE contracts ADD CONSTRAINT FK_950A97353C674EE FOREIGN KEY (offer_id) REFERENCES offers (id);
ALTER TABLE contracts ADD CONSTRAINT FK_950A97397139001 FOREIGN KEY (applicant_id) REFERENCES user (id);
ALTER TABLE contracts ADD CONSTRAINT FK_950A9737E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id);
DROP INDEX offer_id ON contracts;
CREATE INDEX IDX_950A97353C674EE ON contracts (offer_id);
DROP INDEX applicant_id ON contracts;
CREATE INDEX IDX_950A97397139001 ON contracts (applicant_id);
DROP INDEX owner_id ON contracts;
CREATE INDEX IDX_950A9737E3C61F9 ON contracts (owner_id);
ALTER TABLE contracts ADD CONSTRAINT contracts_ibfk_3 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE contracts ADD CONSTRAINT contracts_ibfk_1 FOREIGN KEY (offer_id) REFERENCES offers (id) ON DELETE CASCADE;
ALTER TABLE contracts ADD CONSTRAINT contracts_ibfk_2 FOREIGN KEY (applicant_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE departments DROP FOREIGN KEY fk_dept_manager;
ALTER TABLE departments DROP FOREIGN KEY fk_dept_manager;
ALTER TABLE departments CHANGE description description LONGTEXT DEFAULT NULL, CHANGE allocated_budget allocated_budget DOUBLE PRECISION DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE departments ADD CONSTRAINT FK_16AEB8D4783E3463 FOREIGN KEY (manager_id) REFERENCES user (id);
DROP INDEX fk_dept_manager ON departments;
CREATE INDEX IDX_16AEB8D4783E3463 ON departments (manager_id);
ALTER TABLE departments ADD CONSTRAINT fk_dept_manager FOREIGN KEY (manager_id) REFERENCES user (id) ON DELETE SET NULL;
ALTER TABLE group_members DROP INDEX user_id, ADD UNIQUE INDEX UNIQ_C3A086F3A76ED395 (user_id);
ALTER TABLE group_members DROP INDEX IDX_C3A086F3FE54D947, ADD UNIQUE INDEX UNIQ_C3A086F3FE54D947 (group_id);
ALTER TABLE group_members DROP FOREIGN KEY group_members_ibfk_2;
ALTER TABLE group_members DROP FOREIGN KEY group_members_ibfk_1;
DROP INDEX unique_group_member ON group_members;
ALTER TABLE group_members CHANGE group_id group_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE role role VARCHAR(255) DEFAULT NULL, CHANGE joined_at joined_at DATETIME NOT NULL;
ALTER TABLE group_members ADD CONSTRAINT FK_C3A086F3FE54D947 FOREIGN KEY (group_id) REFERENCES community_groups (id);
ALTER TABLE group_members ADD CONSTRAINT FK_C3A086F3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE interviews DROP FOREIGN KEY interviews_ibfk_3;
ALTER TABLE interviews DROP FOREIGN KEY interviews_ibfk_1;
ALTER TABLE interviews DROP FOREIGN KEY interviews_ibfk_4;
ALTER TABLE interviews DROP FOREIGN KEY interviews_ibfk_2;
ALTER TABLE interviews DROP FOREIGN KEY interviews_ibfk_3;
ALTER TABLE interviews DROP FOREIGN KEY interviews_ibfk_1;
ALTER TABLE interviews DROP FOREIGN KEY interviews_ibfk_4;
ALTER TABLE interviews DROP FOREIGN KEY interviews_ibfk_2;
ALTER TABLE interviews CHANGE organizer_id organizer_id INT DEFAULT NULL, CHANGE candidate_id candidate_id INT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE interviews ADD CONSTRAINT FK_3A752682876C4DDA FOREIGN KEY (organizer_id) REFERENCES user (id);
ALTER TABLE interviews ADD CONSTRAINT FK_3A75268291BD8781 FOREIGN KEY (candidate_id) REFERENCES user (id);
ALTER TABLE interviews ADD CONSTRAINT FK_3A7526823E030ACD FOREIGN KEY (application_id) REFERENCES job_applications (id);
ALTER TABLE interviews ADD CONSTRAINT FK_3A75268253C674EE FOREIGN KEY (offer_id) REFERENCES offers (id);
DROP INDEX organizer_id ON interviews;
CREATE INDEX IDX_3A752682876C4DDA ON interviews (organizer_id);
DROP INDEX candidate_id ON interviews;
CREATE INDEX IDX_3A75268291BD8781 ON interviews (candidate_id);
DROP INDEX application_id ON interviews;
CREATE INDEX IDX_3A7526823E030ACD ON interviews (application_id);
DROP INDEX offer_id ON interviews;
CREATE INDEX IDX_3A75268253C674EE ON interviews (offer_id);
ALTER TABLE interviews ADD CONSTRAINT interviews_ibfk_3 FOREIGN KEY (application_id) REFERENCES job_applications (id) ON DELETE SET NULL;
ALTER TABLE interviews ADD CONSTRAINT interviews_ibfk_1 FOREIGN KEY (organizer_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE interviews ADD CONSTRAINT interviews_ibfk_4 FOREIGN KEY (offer_id) REFERENCES offers (id) ON DELETE SET NULL;
ALTER TABLE interviews ADD CONSTRAINT interviews_ibfk_2 FOREIGN KEY (candidate_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE job_applications DROP FOREIGN KEY job_applications_ibfk_2;
ALTER TABLE job_applications DROP FOREIGN KEY job_applications_ibfk_1;
ALTER TABLE job_applications DROP FOREIGN KEY job_applications_ibfk_2;
ALTER TABLE job_applications DROP FOREIGN KEY job_applications_ibfk_1;
ALTER TABLE job_applications CHANGE offer_id offer_id INT DEFAULT NULL, CHANGE applicant_id applicant_id INT DEFAULT NULL, CHANGE cover_letter cover_letter LONGTEXT DEFAULT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE ai_feedback ai_feedback LONGTEXT DEFAULT NULL, CHANGE applied_at applied_at DATETIME NOT NULL;
ALTER TABLE job_applications ADD CONSTRAINT FK_F8AAF3DF53C674EE FOREIGN KEY (offer_id) REFERENCES offers (id);
ALTER TABLE job_applications ADD CONSTRAINT FK_F8AAF3DF97139001 FOREIGN KEY (applicant_id) REFERENCES user (id);
DROP INDEX offer_id ON job_applications;
CREATE INDEX IDX_F8AAF3DF53C674EE ON job_applications (offer_id);
DROP INDEX applicant_id ON job_applications;
CREATE INDEX IDX_F8AAF3DF97139001 ON job_applications (applicant_id);
ALTER TABLE job_applications ADD CONSTRAINT job_applications_ibfk_2 FOREIGN KEY (applicant_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE job_applications ADD CONSTRAINT job_applications_ibfk_1 FOREIGN KEY (offer_id) REFERENCES offers (id) ON DELETE CASCADE;
ALTER TABLE leaves DROP FOREIGN KEY leaves_ibfk_1;
ALTER TABLE leaves DROP FOREIGN KEY leaves_ibfk_1;
ALTER TABLE leaves CHANGE user_id user_id INT DEFAULT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE reason reason LONGTEXT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE rejection_reason rejection_reason LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE leaves ADD CONSTRAINT FK_9D46AD5FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
DROP INDEX user_id ON leaves;
CREATE INDEX IDX_9D46AD5FA76ED395 ON leaves (user_id);
ALTER TABLE leaves ADD CONSTRAINT leaves_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE messages DROP FOREIGN KEY messages_ibfk_1;
ALTER TABLE messages DROP FOREIGN KEY messages_ibfk_2;
ALTER TABLE messages DROP FOREIGN KEY messages_ibfk_1;
ALTER TABLE messages DROP FOREIGN KEY messages_ibfk_2;
ALTER TABLE messages CHANGE sender_id sender_id INT DEFAULT NULL, CHANGE room_id room_id INT DEFAULT NULL, CHANGE content content LONGTEXT DEFAULT NULL, CHANGE timestamp timestamp DATETIME NOT NULL;
ALTER TABLE messages ADD CONSTRAINT FK_DB021E96F624B39D FOREIGN KEY (sender_id) REFERENCES user (id);
ALTER TABLE messages ADD CONSTRAINT FK_DB021E9654177093 FOREIGN KEY (room_id) REFERENCES chat_rooms (id);
DROP INDEX sender_id ON messages;
CREATE INDEX IDX_DB021E96F624B39D ON messages (sender_id);
DROP INDEX room_id ON messages;
CREATE INDEX IDX_DB021E9654177093 ON messages (room_id);
ALTER TABLE messages ADD CONSTRAINT messages_ibfk_1 FOREIGN KEY (sender_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE messages ADD CONSTRAINT messages_ibfk_2 FOREIGN KEY (room_id) REFERENCES chat_rooms (id) ON DELETE CASCADE;
ALTER TABLE notifications DROP FOREIGN KEY notifications_ibfk_1;
ALTER TABLE notifications DROP FOREIGN KEY notifications_ibfk_1;
ALTER TABLE notifications CHANGE user_id user_id INT DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE body body LONGTEXT DEFAULT NULL, CHANGE reference_type reference_type VARCHAR(255) DEFAULT NULL, CHANGE is_read is_read TINYINT(1) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
DROP INDEX user_id ON notifications;
CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id);
ALTER TABLE notifications ADD CONSTRAINT notifications_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE offers DROP FOREIGN KEY offers_ibfk_1;
ALTER TABLE offers DROP FOREIGN KEY offers_ibfk_2;
ALTER TABLE offers DROP FOREIGN KEY offers_ibfk_1;
ALTER TABLE offers DROP FOREIGN KEY offers_ibfk_2;
ALTER TABLE offers CHANGE title title VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE offer_type offer_type VARCHAR(255) NOT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE required_skills required_skills VARCHAR(255) DEFAULT NULL, CHANGE location location VARCHAR(255) DEFAULT NULL, CHANGE amount amount DOUBLE PRECISION DEFAULT NULL, CHANGE currency currency VARCHAR(255) DEFAULT NULL, CHANGE owner_id owner_id INT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE offers ADD CONSTRAINT FK_DA4604277E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id);
ALTER TABLE offers ADD CONSTRAINT FK_DA460427AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id);
DROP INDEX owner_id ON offers;
CREATE INDEX IDX_DA4604277E3C61F9 ON offers (owner_id);
DROP INDEX department_id ON offers;
CREATE INDEX IDX_DA460427AE80F5DF ON offers (department_id);
ALTER TABLE offers ADD CONSTRAINT offers_ibfk_1 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE offers ADD CONSTRAINT offers_ibfk_2 FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL;
ALTER TABLE payrolls DROP FOREIGN KEY payrolls_ibfk_1;
ALTER TABLE payrolls DROP FOREIGN KEY payrolls_ibfk_1;
ALTER TABLE payrolls CHANGE user_id user_id INT DEFAULT NULL, CHANGE amount amount NUMERIC(10, 2) DEFAULT NULL, CHANGE base_salary base_salary NUMERIC(10, 2) DEFAULT NULL, CHANGE bonus bonus NUMERIC(10, 2) DEFAULT NULL, CHANGE deductions deductions NUMERIC(10, 2) DEFAULT NULL, CHANGE net_salary net_salary NUMERIC(10, 2) DEFAULT NULL, CHANGE total_hours_worked total_hours_worked DOUBLE PRECISION DEFAULT NULL, CHANGE hourly_rate hourly_rate DOUBLE PRECISION DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE generated_at generated_at DATETIME NOT NULL;
ALTER TABLE payrolls ADD CONSTRAINT FK_69403732A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
DROP INDEX user_id ON payrolls;
CREATE INDEX IDX_69403732A76ED395 ON payrolls (user_id);
ALTER TABLE payrolls ADD CONSTRAINT payrolls_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE posts DROP FOREIGN KEY posts_ibfk_1;
ALTER TABLE posts DROP FOREIGN KEY posts_ibfk_2;
ALTER TABLE posts DROP FOREIGN KEY posts_ibfk_1;
ALTER TABLE posts DROP FOREIGN KEY posts_ibfk_2;
ALTER TABLE posts CHANGE author_id author_id INT DEFAULT NULL, CHANGE content content LONGTEXT DEFAULT NULL, CHANGE visibility visibility VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE likes_count likes_count INT DEFAULT NULL, CHANGE comments_count comments_count INT DEFAULT NULL, CHANGE shares_count shares_count INT DEFAULT NULL;
ALTER TABLE posts ADD CONSTRAINT FK_885DBAFAF675F31B FOREIGN KEY (author_id) REFERENCES user (id);
ALTER TABLE posts ADD CONSTRAINT FK_885DBAFAFE54D947 FOREIGN KEY (group_id) REFERENCES community_groups (id);
DROP INDEX author_id ON posts;
CREATE INDEX IDX_885DBAFAF675F31B ON posts (author_id);
DROP INDEX group_id ON posts;
CREATE INDEX IDX_885DBAFAFE54D947 ON posts (group_id);
ALTER TABLE posts ADD CONSTRAINT posts_ibfk_1 FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE posts ADD CONSTRAINT posts_ibfk_2 FOREIGN KEY (group_id) REFERENCES community_groups (id) ON DELETE CASCADE;
ALTER TABLE projects DROP FOREIGN KEY projects_ibfk_2;
ALTER TABLE projects DROP FOREIGN KEY projects_ibfk_1;
ALTER TABLE projects DROP FOREIGN KEY projects_ibfk_2;
ALTER TABLE projects DROP FOREIGN KEY projects_ibfk_1;
ALTER TABLE projects CHANGE description description LONGTEXT DEFAULT NULL, CHANGE owner_id owner_id INT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A47E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id);
ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id);
DROP INDEX owner_id ON projects;
CREATE INDEX IDX_5C93B3A47E3C61F9 ON projects (owner_id);
DROP INDEX department_id ON projects;
CREATE INDEX IDX_5C93B3A4AE80F5DF ON projects (department_id);
ALTER TABLE projects ADD CONSTRAINT projects_ibfk_2 FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL;
ALTER TABLE projects ADD CONSTRAINT projects_ibfk_1 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE project_members DROP INDEX user_id, ADD UNIQUE INDEX UNIQ_D3BEDE9AA76ED395 (user_id);
ALTER TABLE project_members DROP INDEX IDX_D3BEDE9A166D1F9C, ADD UNIQUE INDEX UNIQ_D3BEDE9A166D1F9C (project_id);
ALTER TABLE project_members DROP FOREIGN KEY project_members_ibfk_1;
ALTER TABLE project_members DROP FOREIGN KEY project_members_ibfk_2;
DROP INDEX unique_project_member ON project_members;
ALTER TABLE project_members CHANGE project_id project_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE role role VARCHAR(255) DEFAULT NULL, CHANGE joined_at joined_at DATETIME NOT NULL;
ALTER TABLE project_members ADD CONSTRAINT FK_D3BEDE9A166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id);
ALTER TABLE project_members ADD CONSTRAINT FK_D3BEDE9AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE reactions DROP FOREIGN KEY reactions_ibfk_1;
ALTER TABLE reactions DROP FOREIGN KEY reactions_ibfk_2;
ALTER TABLE reactions DROP FOREIGN KEY reactions_ibfk_1;
ALTER TABLE reactions DROP FOREIGN KEY reactions_ibfk_2;
ALTER TABLE reactions CHANGE post_id post_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE reactions ADD CONSTRAINT FK_38737FB34B89032C FOREIGN KEY (post_id) REFERENCES posts (id);
ALTER TABLE reactions ADD CONSTRAINT FK_38737FB3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
DROP INDEX post_id ON reactions;
CREATE INDEX IDX_38737FB34B89032C ON reactions (post_id);
DROP INDEX user_id ON reactions;
CREATE INDEX IDX_38737FB3A76ED395 ON reactions (user_id);
ALTER TABLE reactions ADD CONSTRAINT reactions_ibfk_1 FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE;
ALTER TABLE reactions ADD CONSTRAINT reactions_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE tasks DROP FOREIGN KEY tasks_ibfk_2;
ALTER TABLE tasks DROP FOREIGN KEY tasks_ibfk_1;
ALTER TABLE tasks DROP FOREIGN KEY tasks_ibfk_2;
ALTER TABLE tasks DROP FOREIGN KEY tasks_ibfk_1;
ALTER TABLE tasks CHANGE project_id project_id INT DEFAULT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE priority priority VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE submission_text submission_text LONGTEXT DEFAULT NULL, CHANGE submission_file submission_file VARCHAR(255) DEFAULT NULL, CHANGE review_status review_status VARCHAR(255) DEFAULT NULL, CHANGE review_feedback review_feedback LONGTEXT DEFAULT NULL;
ALTER TABLE tasks ADD CONSTRAINT FK_50586597166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id);
ALTER TABLE tasks ADD CONSTRAINT FK_5058659789EEAF91 FOREIGN KEY (assigned_to) REFERENCES user (id);
DROP INDEX project_id ON tasks;
CREATE INDEX IDX_50586597166D1F9C ON tasks (project_id);
DROP INDEX assigned_to ON tasks;
CREATE INDEX IDX_5058659789EEAF91 ON tasks (assigned_to);
ALTER TABLE tasks ADD CONSTRAINT tasks_ibfk_2 FOREIGN KEY (assigned_to) REFERENCES user (id) ON DELETE SET NULL;
ALTER TABLE tasks ADD CONSTRAINT tasks_ibfk_1 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE training_certificates DROP FOREIGN KEY training_certificates_ibfk_3;
ALTER TABLE training_certificates DROP FOREIGN KEY training_certificates_ibfk_1;
ALTER TABLE training_certificates DROP FOREIGN KEY training_certificates_ibfk_2;
DROP INDEX certificate_number ON training_certificates;
ALTER TABLE training_certificates DROP FOREIGN KEY training_certificates_ibfk_3;
ALTER TABLE training_certificates DROP FOREIGN KEY training_certificates_ibfk_1;
ALTER TABLE training_certificates DROP FOREIGN KEY training_certificates_ibfk_2;
ALTER TABLE training_certificates CHANGE enrollment_id enrollment_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE course_id course_id INT DEFAULT NULL, CHANGE certificate_number certificate_number VARCHAR(255) NOT NULL, CHANGE issued_at issued_at DATETIME NOT NULL;
ALTER TABLE training_certificates ADD CONSTRAINT FK_9535D7528F7DB25B FOREIGN KEY (enrollment_id) REFERENCES training_enrollments (id);
ALTER TABLE training_certificates ADD CONSTRAINT FK_9535D752A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE training_certificates ADD CONSTRAINT FK_9535D752591CC992 FOREIGN KEY (course_id) REFERENCES training_courses (id);
DROP INDEX enrollment_id ON training_certificates;
CREATE INDEX IDX_9535D7528F7DB25B ON training_certificates (enrollment_id);
DROP INDEX user_id ON training_certificates;
CREATE INDEX IDX_9535D752A76ED395 ON training_certificates (user_id);
DROP INDEX course_id ON training_certificates;
CREATE INDEX IDX_9535D752591CC992 ON training_certificates (course_id);
ALTER TABLE training_certificates ADD CONSTRAINT training_certificates_ibfk_3 FOREIGN KEY (course_id) REFERENCES training_courses (id) ON DELETE CASCADE;
ALTER TABLE training_certificates ADD CONSTRAINT training_certificates_ibfk_1 FOREIGN KEY (enrollment_id) REFERENCES training_enrollments (id) ON DELETE CASCADE;
ALTER TABLE training_certificates ADD CONSTRAINT training_certificates_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE training_courses DROP FOREIGN KEY training_courses_ibfk_1;
ALTER TABLE training_courses DROP FOREIGN KEY training_courses_ibfk_1;
ALTER TABLE training_courses CHANGE description description LONGTEXT DEFAULT NULL, CHANGE category category VARCHAR(255) DEFAULT NULL, CHANGE difficulty difficulty VARCHAR(255) DEFAULT NULL, CHANGE duration_hours duration_hours DOUBLE PRECISION DEFAULT NULL, CHANGE mega_link mega_link LONGTEXT DEFAULT NULL, CHANGE thumbnail_url thumbnail_url LONGTEXT DEFAULT NULL, CHANGE max_participants max_participants INT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE quiz_timer_seconds quiz_timer_seconds INT DEFAULT NULL;
ALTER TABLE training_courses ADD CONSTRAINT FK_749BCA42DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id);
DROP INDEX created_by ON training_courses;
CREATE INDEX IDX_749BCA42DE12AB56 ON training_courses (created_by);
ALTER TABLE training_courses ADD CONSTRAINT training_courses_ibfk_1 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL;
ALTER TABLE training_enrollments DROP INDEX user_id, ADD UNIQUE INDEX UNIQ_68B3BBE5A76ED395 (user_id);
ALTER TABLE training_enrollments DROP INDEX IDX_68B3BBE5591CC992, ADD UNIQUE INDEX UNIQ_68B3BBE5591CC992 (course_id);
ALTER TABLE training_enrollments DROP FOREIGN KEY training_enrollments_ibfk_2;
ALTER TABLE training_enrollments DROP FOREIGN KEY training_enrollments_ibfk_1;
DROP INDEX unique_enrollment ON training_enrollments;
ALTER TABLE training_enrollments CHANGE course_id course_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE progress progress INT DEFAULT NULL, CHANGE enrolled_at enrolled_at DATETIME NOT NULL;
ALTER TABLE training_enrollments ADD CONSTRAINT FK_68B3BBE5591CC992 FOREIGN KEY (course_id) REFERENCES training_courses (id);
ALTER TABLE training_enrollments ADD CONSTRAINT FK_68B3BBE5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE user DROP FOREIGN KEY user_ibfk_1;
DROP INDEX email ON user;
ALTER TABLE user DROP FOREIGN KEY user_ibfk_1;
ALTER TABLE user CHANGE first_name first_name VARCHAR(255) NOT NULL, CHANGE last_name last_name VARCHAR(255) NOT NULL, CHANGE role role VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE avatar_path avatar_path VARCHAR(255) DEFAULT NULL, CHANGE face_encoding face_encoding LONGTEXT DEFAULT NULL, CHANGE is_online is_online TINYINT(1) DEFAULT NULL, CHANGE is_verified is_verified TINYINT(1) DEFAULT NULL, CHANGE is_active is_active TINYINT(1) DEFAULT NULL, CHANGE hourly_rate hourly_rate DOUBLE PRECISION DEFAULT NULL, CHANGE monthly_salary monthly_salary DOUBLE PRECISION DEFAULT NULL, CHANGE bio bio LONGTEXT DEFAULT NULL;
ALTER TABLE user ADD CONSTRAINT FK_8D93D649AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id);
DROP INDEX department_id ON user;
CREATE INDEX IDX_8D93D649AE80F5DF ON user (department_id);
ALTER TABLE user ADD CONSTRAINT user_ibfk_1 FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL;
ALTER TABLE user_follows DROP INDEX followed_id, ADD UNIQUE INDEX UNIQ_136E9479D956F010 (followed_id);
ALTER TABLE user_follows DROP INDEX IDX_136E9479AC24F853, ADD UNIQUE INDEX UNIQ_136E9479AC24F853 (follower_id);
ALTER TABLE user_follows DROP FOREIGN KEY user_follows_ibfk_2;
ALTER TABLE user_follows DROP FOREIGN KEY user_follows_ibfk_1;
DROP INDEX unique_follow ON user_follows;
ALTER TABLE user_follows CHANGE follower_id follower_id INT DEFAULT NULL, CHANGE followed_id followed_id INT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE user_follows ADD CONSTRAINT FK_136E9479AC24F853 FOREIGN KEY (follower_id) REFERENCES user (id);
ALTER TABLE user_follows ADD CONSTRAINT FK_136E9479D956F010 FOREIGN KEY (followed_id) REFERENCES user (id);
