<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DVuzknService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dVuzkn_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repo' => ['privates', 'App\\Repository\\ContractRepository', 'getContractRepositoryService', true],
        ], [
            'paginator' => '?',
            'repo' => 'App\\Repository\\ContractRepository',
        ]);

        if (isset($container->privates['.service_locator.dVuzkn_'])) {
            return $container->privates['.service_locator.dVuzkn_'];
        }

        return $container->privates['.service_locator.dVuzkn_'] = $instance;
    }
}
