<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QV9Bs1YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qV9Bs1Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qV9Bs1Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentRepo' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'groupRepo' => ['privates', 'App\\Repository\\CommunityGroupRepository', 'getCommunityGroupRepositoryService', true],
            'post' => ['privates', '.errored..service_locator.qV9Bs1Y.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.qV9Bs1Y": it needs an instance of "App\\Entity\\Post" but this type has been excluded in "config/services.yaml".'],
        ], [
            'commentRepo' => 'App\\Repository\\CommentRepository',
            'em' => '?',
            'groupRepo' => 'App\\Repository\\CommunityGroupRepository',
            'post' => 'App\\Entity\\Post',
        ]);
    }
}
