<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MLr4rXeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mLr4rXe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mLr4rXe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activeRoom' => ['privates', '.errored..service_locator.mLr4rXe.App\\Entity\\ChatRoom', NULL, 'Cannot autowire service ".service_locator.mLr4rXe": it needs an instance of "App\\Entity\\ChatRoom" but this type has been excluded in "config/services.yaml".'],
            'memberRepo' => ['privates', 'App\\Repository\\ChatRoomMemberRepository', 'getChatRoomMemberRepositoryService', true],
            'msgRepo' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'activeRoom' => 'App\\Entity\\ChatRoom',
            'memberRepo' => 'App\\Repository\\ChatRoomMemberRepository',
            'msgRepo' => 'App\\Repository\\MessageRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
