<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BXjO9SaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bXjO9Sa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certRepo' => ['privates', 'App\\Repository\\TrainingCertificateRepository', 'getTrainingCertificateRepositoryService', true],
            'courseRepo' => ['privates', 'App\\Repository\\TrainingCourseRepository', 'getTrainingCourseRepositoryService', true],
            'enrollRepo' => ['privates', 'App\\Repository\\TrainingEnrollmentRepository', 'getTrainingEnrollmentRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'certRepo' => 'App\\Repository\\TrainingCertificateRepository',
            'courseRepo' => 'App\\Repository\\TrainingCourseRepository',
            'enrollRepo' => 'App\\Repository\\TrainingEnrollmentRepository',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.bXjO9Sa'])) {
            return $container->privates['.service_locator.bXjO9Sa'];
        }

        return $container->privates['.service_locator.bXjO9Sa'] = $instance;
    }
}
