<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9BqGMU5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9BqGMU5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9BqGMU5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aiInsightService' => ['privates', 'App\\Service\\OfferAiInsightService', 'getOfferAiInsightServiceService', true],
            'appRepo' => ['privates', 'App\\Repository\\JobApplicationRepository', 'getJobApplicationRepositoryService', true],
            'matchService' => ['privates', 'App\\Service\\ApplicationMatchService', 'getApplicationMatchServiceService', true],
            'offer' => ['privates', '.errored..service_locator.9BqGMU5.App\\Entity\\Offer', NULL, 'Cannot autowire service ".service_locator.9BqGMU5": it needs an instance of "App\\Entity\\Offer" but this type has been excluded in "config/services.yaml".'],
        ], [
            'aiInsightService' => 'App\\Service\\OfferAiInsightService',
            'appRepo' => 'App\\Repository\\JobApplicationRepository',
            'matchService' => 'App\\Service\\ApplicationMatchService',
            'offer' => 'App\\Entity\\Offer',
        ]);
    }
}
