<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J8TL6DiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j8TL6Di' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j8TL6Di'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certificate' => ['privates', '.errored..service_locator.j8TL6Di.App\\Entity\\TrainingCertificate', NULL, 'Cannot autowire service ".service_locator.j8TL6Di": it needs an instance of "App\\Entity\\TrainingCertificate" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'certificate' => 'App\\Entity\\TrainingCertificate',
            'em' => '?',
        ]);
    }
}
