<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3Nb1VDnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3Nb1VDn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3Nb1VDn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'payroll' => ['privates', '.errored..service_locator.3Nb1VDn.App\\Entity\\Payroll', NULL, 'Cannot autowire service ".service_locator.3Nb1VDn": it needs an instance of "App\\Entity\\Payroll" but this type has been excluded in "config/services.yaml".'],
        ], [
            'payroll' => 'App\\Entity\\Payroll',
        ]);
    }
}
