<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SWNzzDTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SWNzzDT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SWNzzDT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'memberRepo' => ['privates', 'App\\Repository\\ChatRoomMemberRepository', 'getChatRoomMemberRepositoryService', true],
            'room' => ['privates', '.errored..service_locator.SWNzzDT.App\\Entity\\ChatRoom', NULL, 'Cannot autowire service ".service_locator.SWNzzDT": it needs an instance of "App\\Entity\\ChatRoom" but this type has been excluded in "config/services.yaml".'],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'memberRepo' => 'App\\Repository\\ChatRoomMemberRepository',
            'room' => 'App\\Entity\\ChatRoom',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
