<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pl40kEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._pl40kE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._pl40kE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'payroll' => ['privates', '.errored..service_locator._pl40kE.App\\Entity\\Payroll', NULL, 'Cannot autowire service ".service_locator._pl40kE": it needs an instance of "App\\Entity\\Payroll" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'payroll' => 'App\\Entity\\Payroll',
        ]);
    }
}
