<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AZhMsoqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aZhMsoq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aZhMsoq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'groupRepo' => ['privates', 'App\\Repository\\CommunityGroupRepository', 'getCommunityGroupRepositoryService', true],
            'postRepo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'em' => '?',
            'groupRepo' => 'App\\Repository\\CommunityGroupRepository',
            'postRepo' => 'App\\Repository\\PostRepository',
        ]);
    }
}
