<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TM_KEeSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TM.KEeS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TM.KEeS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'course' => ['privates', '.errored..service_locator.TM.KEeS.App\\Entity\\TrainingCourse', NULL, 'Cannot autowire service ".service_locator.TM.KEeS": it needs an instance of "App\\Entity\\TrainingCourse" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'enrollRepo' => ['privates', 'App\\Repository\\TrainingEnrollmentRepository', 'getTrainingEnrollmentRepositoryService', true],
        ], [
            'course' => 'App\\Entity\\TrainingCourse',
            'em' => '?',
            'enrollRepo' => 'App\\Repository\\TrainingEnrollmentRepository',
        ]);
    }
}
