<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X8zQOK0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X8zQOK0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X8zQOK0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'memberRepo' => ['privates', 'App\\Repository\\ChatRoomMemberRepository', 'getChatRoomMemberRepositoryService', true],
            'msgRepo' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'memberRepo' => 'App\\Repository\\ChatRoomMemberRepository',
            'msgRepo' => 'App\\Repository\\MessageRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
