<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SIGCXPPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SIGCXPP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SIGCXPP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'application' => ['privates', '.errored..service_locator.SIGCXPP.App\\Entity\\JobApplication', NULL, 'Cannot autowire service ".service_locator.SIGCXPP": it needs an instance of "App\\Entity\\JobApplication" but this type has been excluded in "config/services.yaml".'],
        ], [
            'application' => 'App\\Entity\\JobApplication',
        ]);
    }
}
