<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CDZ0sRcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CDZ0sRc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CDZ0sRc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'call' => ['privates', '.errored..service_locator.CDZ0sRc.App\\Entity\\Call', NULL, 'Cannot autowire service ".service_locator.CDZ0sRc": it needs an instance of "App\\Entity\\Call" but this type has been excluded in "config/services.yaml".'],
        ], [
            'call' => 'App\\Entity\\Call',
        ]);
    }
}
