<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ISq8feVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iSq8feV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iSq8feV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'leave' => ['privates', '.errored..service_locator.iSq8feV.App\\Entity\\Leave', NULL, 'Cannot autowire service ".service_locator.iSq8feV": it needs an instance of "App\\Entity\\Leave" but this type has been excluded in "config/services.yaml".'],
            'repo' => ['privates', 'App\\Repository\\LeaveRepository', 'getLeaveRepositoryService', true],
        ], [
            'leave' => 'App\\Entity\\Leave',
            'repo' => 'App\\Repository\\LeaveRepository',
        ]);
    }
}
