<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F5pHpfPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f5pHpfP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repo' => ['privates', 'App\\Repository\\JobApplicationRepository', 'getJobApplicationRepositoryService', true],
        ], [
            'paginator' => '?',
            'repo' => 'App\\Repository\\JobApplicationRepository',
        ]);

        if (isset($container->privates['.service_locator.f5pHpfP'])) {
            return $container->privates['.service_locator.f5pHpfP'];
        }

        return $container->privates['.service_locator.f5pHpfP'] = $instance;
    }
}
