<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ItELOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._it_ELO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._it_ELO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'room' => ['privates', '.errored..service_locator._it_ELO.App\\Entity\\ChatRoom', NULL, 'Cannot autowire service ".service_locator._it_ELO": it needs an instance of "App\\Entity\\ChatRoom" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'em' => '?',
            'room' => 'App\\Entity\\ChatRoom',
            'slugger' => '?',
        ]);
    }
}
