<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RGPlsYKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rGPlsYK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rGPlsYK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'task' => ['privates', '.errored..service_locator.rGPlsYK.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.rGPlsYK": it needs an instance of "App\\Entity\\Task" but this type has been excluded in "config/services.yaml".'],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'em' => '?',
            'task' => 'App\\Entity\\Task',
            'validator' => '?',
        ]);
    }
}
