<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MG66gsGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mG66gsG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mG66gsG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'date' => ['privates', '.errored..service_locator.mG66gsG.DateTimeInterface', NULL, 'Cannot autowire service ".service_locator.mG66gsG": it references interface "DateTimeInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'date' => 'DateTimeInterface',
        ]);
    }
}
