<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LkPWsDhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LkPWsDh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LkPWsDh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contract' => ['privates', '.errored..service_locator.LkPWsDh.App\\Entity\\Contract', NULL, 'Cannot autowire service ".service_locator.LkPWsDh": it needs an instance of "App\\Entity\\Contract" but this type has been excluded in "config/services.yaml".'],
        ], [
            'contract' => 'App\\Entity\\Contract',
        ]);
    }
}
