<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZXebIIWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZXebIIW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZXebIIW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certRepo' => ['privates', 'App\\Repository\\TrainingCertificateRepository', 'getTrainingCertificateRepositoryService', true],
            'course' => ['privates', '.errored..service_locator.ZXebIIW.App\\Entity\\TrainingCourse', NULL, 'Cannot autowire service ".service_locator.ZXebIIW": it needs an instance of "App\\Entity\\TrainingCourse" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'enrollRepo' => ['privates', 'App\\Repository\\TrainingEnrollmentRepository', 'getTrainingEnrollmentRepositoryService', true],
            'n8n' => ['privates', 'App\\Service\\N8nWebhookService', 'getN8nWebhookServiceService', true],
            'notifier' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
        ], [
            'certRepo' => 'App\\Repository\\TrainingCertificateRepository',
            'course' => 'App\\Entity\\TrainingCourse',
            'em' => '?',
            'enrollRepo' => 'App\\Repository\\TrainingEnrollmentRepository',
            'n8n' => 'App\\Service\\N8nWebhookService',
            'notifier' => 'App\\Service\\NotificationService',
        ]);
    }
}
