<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1k7c5fQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1k7c5fQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1k7c5fQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attendanceRepo' => ['privates', 'App\\Repository\\AttendanceRepository', 'getAttendanceRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'n8n' => ['privates', 'App\\Service\\N8nWebhookService', 'getN8nWebhookServiceService', true],
            'notifier' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
            'payrollRepo' => ['privates', 'App\\Repository\\PayrollRepository', 'getPayrollRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'attendanceRepo' => 'App\\Repository\\AttendanceRepository',
            'em' => '?',
            'n8n' => 'App\\Service\\N8nWebhookService',
            'notifier' => 'App\\Service\\NotificationService',
            'payrollRepo' => 'App\\Repository\\PayrollRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
