<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KNJUg_AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KNJUg.a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KNJUg.a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'call' => ['privates', '.errored..service_locator.KNJUg.a.App\\Entity\\Call', NULL, 'Cannot autowire service ".service_locator.KNJUg.a": it needs an instance of "App\\Entity\\Call" but this type has been excluded in "config/services.yaml".'],
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
        ], [
            'call' => 'App\\Entity\\Call',
            'csrfTokenManager' => '?',
        ]);
    }
}
