<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MRUC5fzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mRUC5fz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mRUC5fz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'call' => ['privates', '.errored..service_locator.mRUC5fz.App\\Entity\\Call', NULL, 'Cannot autowire service ".service_locator.mRUC5fz": it needs an instance of "App\\Entity\\Call" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'signalRepo' => ['privates', 'App\\Repository\\CallSignalRepository', 'getCallSignalRepositoryService', true],
        ], [
            'call' => 'App\\Entity\\Call',
            'em' => '?',
            'signalRepo' => 'App\\Repository\\CallSignalRepository',
        ]);
    }
}
