<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RGEtQNxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RGEtQNx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RGEtQNx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attendanceRepo' => ['privates', 'App\\Repository\\AttendanceRepository', 'getAttendanceRepositoryService', true],
            'deptRepo' => ['privates', 'App\\Repository\\DepartmentRepository', 'getDepartmentRepositoryService', true],
            'leaveRepo' => ['privates', 'App\\Repository\\LeaveRepository', 'getLeaveRepositoryService', true],
            'payrollRepo' => ['privates', 'App\\Repository\\PayrollRepository', 'getPayrollRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'attendanceRepo' => 'App\\Repository\\AttendanceRepository',
            'deptRepo' => 'App\\Repository\\DepartmentRepository',
            'leaveRepo' => 'App\\Repository\\LeaveRepository',
            'payrollRepo' => 'App\\Repository\\PayrollRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
