<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AWks_NAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AWks.NA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AWks.NA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'leave' => ['privates', '.errored..service_locator.AWks.NA.App\\Entity\\Leave', NULL, 'Cannot autowire service ".service_locator.AWks.NA": it needs an instance of "App\\Entity\\Leave" but this type has been excluded in "config/services.yaml".'],
            'n8n' => ['privates', 'App\\Service\\N8nWebhookService', 'getN8nWebhookServiceService', true],
            'notifier' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
            'repo' => ['privates', 'App\\Repository\\LeaveRepository', 'getLeaveRepositoryService', true],
        ], [
            'em' => '?',
            'leave' => 'App\\Entity\\Leave',
            'n8n' => 'App\\Service\\N8nWebhookService',
            'notifier' => 'App\\Service\\NotificationService',
            'repo' => 'App\\Repository\\LeaveRepository',
        ]);
    }
}
