<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UsC4suHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UsC4suH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UsC4suH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'leave' => ['privates', '.errored..service_locator.UsC4suH.App\\Entity\\Leave', NULL, 'Cannot autowire service ".service_locator.UsC4suH": it needs an instance of "App\\Entity\\Leave" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'leave' => 'App\\Entity\\Leave',
        ]);
    }
}
