<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator___9VsKwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator...9VsKw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator...9VsKw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'group' => ['privates', '.errored..service_locator...9VsKw.App\\Entity\\CommunityGroup', NULL, 'Cannot autowire service ".service_locator...9VsKw": it needs an instance of "App\\Entity\\CommunityGroup" but this type has been excluded in "config/services.yaml".'],
            'groupRepo' => ['privates', 'App\\Repository\\CommunityGroupRepository', 'getCommunityGroupRepositoryService', true],
            'postRepo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'em' => '?',
            'group' => 'App\\Entity\\CommunityGroup',
            'groupRepo' => 'App\\Repository\\CommunityGroupRepository',
            'postRepo' => 'App\\Repository\\PostRepository',
        ]);
    }
}
