<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DvYdQxpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DvYdQxp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DvYdQxp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'callRepo' => ['privates', 'App\\Repository\\CallRepository', 'getCallRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'memberRepo' => ['privates', 'App\\Repository\\ChatRoomMemberRepository', 'getChatRoomMemberRepositoryService', true],
            'roomRepo' => ['privates', 'App\\Repository\\ChatRoomRepository', 'getChatRoomRepositoryService', true],
        ], [
            'callRepo' => 'App\\Repository\\CallRepository',
            'em' => '?',
            'memberRepo' => 'App\\Repository\\ChatRoomMemberRepository',
            'roomRepo' => 'App\\Repository\\ChatRoomRepository',
        ]);
    }
}
