<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ApLJUzUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ApLJUzU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ApLJUzU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'callRepo' => ['privates', 'App\\Repository\\CallRepository', 'getCallRepositoryService', true],
            'signalRepo' => ['privates', 'App\\Repository\\CallSignalRepository', 'getCallSignalRepositoryService', true],
        ], [
            'callRepo' => 'App\\Repository\\CallRepository',
            'signalRepo' => 'App\\Repository\\CallSignalRepository',
        ]);
    }
}
