<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9JqBMVdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9JqBMVd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9JqBMVd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'appRepo' => ['privates', 'App\\Repository\\JobApplicationRepository', 'getJobApplicationRepositoryService', true],
            'attendanceRepo' => ['privates', 'App\\Repository\\AttendanceRepository', 'getAttendanceRepositoryService', true],
            'chatRoomRepo' => ['privates', 'App\\Repository\\ChatRoomRepository', 'getChatRoomRepositoryService', true],
            'contractRepo' => ['privates', 'App\\Repository\\ContractRepository', 'getContractRepositoryService', true],
            'deptRepo' => ['privates', 'App\\Repository\\DepartmentRepository', 'getDepartmentRepositoryService', true],
            'interviewRepo' => ['privates', 'App\\Repository\\InterviewRepository', 'getInterviewRepositoryService', true],
            'leaveRepo' => ['privates', 'App\\Repository\\LeaveRepository', 'getLeaveRepositoryService', true],
            'messageRepo' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'notifRepo' => ['privates', 'App\\Repository\\NotificationRepository', 'getNotificationRepositoryService', true],
            'offerRepo' => ['privates', 'App\\Repository\\OfferRepository', 'getOfferRepositoryService', true],
            'payrollRepo' => ['privates', 'App\\Repository\\PayrollRepository', 'getPayrollRepositoryService', true],
            'postRepo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'projectRepo' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
            'taskRepo' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'trainingRepo' => ['privates', 'App\\Repository\\TrainingCourseRepository', 'getTrainingCourseRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'appRepo' => 'App\\Repository\\JobApplicationRepository',
            'attendanceRepo' => 'App\\Repository\\AttendanceRepository',
            'chatRoomRepo' => 'App\\Repository\\ChatRoomRepository',
            'contractRepo' => 'App\\Repository\\ContractRepository',
            'deptRepo' => 'App\\Repository\\DepartmentRepository',
            'interviewRepo' => 'App\\Repository\\InterviewRepository',
            'leaveRepo' => 'App\\Repository\\LeaveRepository',
            'messageRepo' => 'App\\Repository\\MessageRepository',
            'notifRepo' => 'App\\Repository\\NotificationRepository',
            'offerRepo' => 'App\\Repository\\OfferRepository',
            'payrollRepo' => 'App\\Repository\\PayrollRepository',
            'postRepo' => 'App\\Repository\\PostRepository',
            'projectRepo' => 'App\\Repository\\ProjectRepository',
            'taskRepo' => 'App\\Repository\\TaskRepository',
            'trainingRepo' => 'App\\Repository\\TrainingCourseRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
