<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NxZaCwaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NxZaCwa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NxZaCwa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certRepo' => ['privates', 'App\\Repository\\TrainingCertificateRepository', 'getTrainingCertificateRepositoryService', true],
            'course' => ['privates', '.errored..service_locator.NxZaCwa.App\\Entity\\TrainingCourse', NULL, 'Cannot autowire service ".service_locator.NxZaCwa": it needs an instance of "App\\Entity\\TrainingCourse" but this type has been excluded in "config/services.yaml".'],
            'enrollRepo' => ['privates', 'App\\Repository\\TrainingEnrollmentRepository', 'getTrainingEnrollmentRepositoryService', true],
        ], [
            'certRepo' => 'App\\Repository\\TrainingCertificateRepository',
            'course' => 'App\\Entity\\TrainingCourse',
            'enrollRepo' => 'App\\Repository\\TrainingEnrollmentRepository',
        ]);
    }
}
