<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAIServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AIService' shared autowired service.
     *
     * @return \App\Service\AIService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AIService.php';

        return $container->privates['App\\Service\\AIService'] = new \App\Service\AIService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $container->getEnv('default::ZAI_API_KEY'), $container->getEnv('default::GROQ_API_KEY'), $container->getEnv('default::OPENROUTER_API_KEY'), $container->getEnv('default::OPENCODE_API_KEY'));
    }
}
