<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContract4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LkPWsDh.App\Entity\Contract' shared service.
     *
     * @return \App\Entity\Contract
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LkPWsDh": it needs an instance of "App\\Entity\\Contract" but this type has been excluded in "config/services.yaml".');
    }
}
