<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCall4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mRUC5fz.App\Entity\Call' shared service.
     *
     * @return \App\Entity\Call
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mRUC5fz": it needs an instance of "App\\Entity\\Call" but this type has been excluded in "config/services.yaml".');
    }
}
