<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommunityGroupService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator...9VsKw.App\Entity\CommunityGroup' shared service.
     *
     * @return \App\Entity\CommunityGroup
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator...9VsKw": it needs an instance of "App\\Entity\\CommunityGroup" but this type has been excluded in "config/services.yaml".');
    }
}
