<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatRoom2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._it_ELO.App\Entity\ChatRoom' shared service.
     *
     * @return \App\Entity\ChatRoom
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._it_ELO": it needs an instance of "App\\Entity\\ChatRoom" but this type has been excluded in "config/services.yaml".');
    }
}
