<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInterview2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XLu3_h8.App\Entity\Interview' shared service.
     *
     * @return \App\Entity\Interview
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.XLu3_h8": it needs an instance of "App\\Entity\\Interview" but this type has been excluded in "config/services.yaml".');
    }
}
