<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeaveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AWks.NA.App\Entity\Leave' shared service.
     *
     * @return \App\Entity\Leave
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AWks.NA": it needs an instance of "App\\Entity\\Leave" but this type has been excluded in "config/services.yaml".');
    }
}
