<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Handler_DeprecationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'monolog.handler.deprecation' shared service.
     *
     * @return \Monolog\Handler\RotatingFileHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['monolog.handler.deprecation'] = $instance = new \Monolog\Handler\RotatingFileHandler((\dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'log/deprecations.log'), 0, 'info', true, NULL, false);

        $instance->pushProcessor(($container->privates['monolog.processor.psr_log_message'] ??= new \Monolog\Processor\PsrLogMessageProcessor()));
        $instance->setFilenameFormat('{filename}-{date}', 'Y-m-d');

        return $instance;
    }
}
