<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getN8nWebhookServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\N8nWebhookService' shared autowired service.
     *
     * @return \App\Service\N8nWebhookService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'N8nWebhookService.php';

        return $container->privates['App\\Service\\N8nWebhookService'] = new \App\Service\N8nWebhookService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $container->getEnv('default:n8n_default:N8N_BASE_URL'));
    }
}
