<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfferAiInsightServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\OfferAiInsightService' shared autowired service.
     *
     * @return \App\Service\OfferAiInsightService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OfferAiInsightService.php';

        return $container->privates['App\\Service\\OfferAiInsightService'] = new \App\Service\OfferAiInsightService(($container->privates['App\\Service\\AIService'] ?? $container->load('getAIServiceService')));
    }
}
