<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrainingCourseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..xiKTT1.App\Entity\TrainingCourse' shared service.
     *
     * @return \App\Entity\TrainingCourse
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..xiKTT1": it needs an instance of "App\\Entity\\TrainingCourse" but this type has been excluded in "config/services.yaml".');
    }
}
