<?php

namespace ContainerRyoSlHL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrainingCertificateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.j8TL6Di.App\Entity\TrainingCertificate' shared service.
     *
     * @return \App\Entity\TrainingCertificate
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.j8TL6Di": it needs an instance of "App\\Entity\\TrainingCertificate" but this type has been excluded in "config/services.yaml".');
    }
}
