<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRyoSlHL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRyoSlHL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRyoSlHL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRyoSlHL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRyoSlHL\App_KernelDevDebugContainer([
    'container.build_hash' => 'RyoSlHL',
    'container.build_id' => '9df3c773',
    'container.build_time' => 1775564434,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRyoSlHL');
